# Generated by Django 5.2.4 on 2025-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standbyapp', '0005_remove_item_image_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
